comment: off

coverage:
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: auto
      sha256:
        flags:
          - sha256
      sha512:
        flags:
          - sha512
flags:
  sha256:
    paths:
      - packages/sha256/src
  sha512:
    paths:
      - packages/sha512